version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all-actions:
        patterns:
          - "*"
    labels:
      - dependencies
    commit-message:
      prefix: chore
